#!/usr/bin/env python3
"""Generate a module-level progress report for ChronoEHR-Agent."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd


PROJECT = Path(__file__).resolve().parents[2]
REGISTRY = PROJECT / "configs" / "study_registry.json"


def load_registry(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def exists(project: Path, relative_path: str) -> bool:
    return (project / relative_path).exists()


def status_label(percent: int) -> str:
    if percent >= 90:
        return "stable"
    if percent >= 70:
        return "usable"
    if percent >= 45:
        return "prototype"
    if percent >= 20:
        return "scaffold"
    return "planned"


def metric_dict(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    df = pd.read_csv(path)
    if not {"metric", "value"}.issubset(df.columns):
        return {}
    return df.set_index("metric")["value"].astype(str).to_dict()


def study_summary(project: Path, registry: dict[str, Any]) -> list[str]:
    lines = []
    for study in registry.get("studies", []):
        cohort = study.get("cohort", "NA")
        path = project / "outputs" / "tables" / f"mimic_{cohort}_cohort_summary.csv"
        metrics = metric_dict(path)
        if metrics:
            lines.append(
                f"- `{study['id']}` ({cohort}, status={study.get('status', 'NA')}): "
                f"{int(float(metrics.get('final_index_admissions', 0))):,} admissions, "
                f"{int(float(metrics.get('final_subjects', 0))):,} subjects, "
                f"30-day readmission {float(metrics.get('readmission_30d_rate', 0)):.2%}."
            )
        else:
            lines.append(f"- `{study['id']}` ({cohort}, status={study.get('status', 'NA')}): no cohort summary found.")
    return lines


def module_status(project: Path) -> list[dict[str, Any]]:
    modules = [
        {
            "module": "Study Design Agent",
            "percent": 86,
            "evidence": [
                "docs/agent_design.md",
                "docs/study_protocol.md",
                "docs/ckd_mimic_demo_protocol.md",
                "docs/multidatabase_expansion_plan.md",
                "docs/multidatabase_task_matrix.csv",
                "docs/eicu_charls_next_steps.md",
                "docs/mainline_mvp_definition.md",
                "docs/quickstart_usage.md",
                "docs/eicu_temporal_mortality_protocol.md",
                "docs/charls_incident_diabetes_protocol.md",
                "configs/diabetes_mimic_readmission.yaml",
                "configs/ckd_mimic_readmission.yaml",
                "configs/heart_failure_mimic_readmission.yaml",
                "configs/hypertension_mimic_readmission.yaml",
                "configs/eicu_temporal_mortality_template.yaml",
                "configs/charls_incident_diabetes_template.yaml",
                "configs/prediction_time_model_specs.json",
                "configs/feature_window_specs.json",
            ],
            "done": "已有 Agent 设计、糖尿病/CKD protocol、四个慢病 study config、study registry、prediction-time model specs、feature-window specs、MIMIC/CDSL/eICU/CHARLS 多数据库扩展计划、主线 MVP 定义文档、快速使用说明，以及 eICU/CHARLS planned study protocol/config 模板。",
            "next": "继续把 cohort definition 和 report 模板外移到配置；eICU 已进入 baseline-ready 外部 ICU benchmark，CHARLS 数据落地后优先做 readiness 和 wave 字段映射。",
        },
        {
            "module": "Cohort Agent",
            "percent": 86,
            "evidence": [
                "src/chrono_ehr/mimic_diabetes_cohort.py",
                "src/chrono_ehr/mimic_ckd_cohort.py",
                "src/chrono_ehr/mimic_heart_failure_cohort.py",
                "src/chrono_ehr/mimic_hypertension_cohort.py",
                "src/chrono_ehr/mimic_diagnosis_cohort_builder.py",
                "src/chrono_ehr/study_config_loader.py",
                "src/chrono_ehr/validate_diagnosis_cohort_builder.py",
                "src/chrono_ehr/validate_config_code_rules.py",
                "src/chrono_ehr/validate_study_config_schema.py",
                "data/processed/mimic_diabetes_readmission_cohort.csv",
                "data/processed/mimic_ckd_readmission_cohort.csv",
                "data/processed/mimic_heart_failure_readmission_cohort.csv",
                "data/processed/mimic_hypertension_readmission_cohort.csv",
                "outputs/tables/mimic_diabetes_cohort_summary.csv",
                "outputs/tables/mimic_ckd_cohort_summary.csv",
                "outputs/tables/mimic_heart_failure_cohort_summary.csv",
                "outputs/tables/mimic_hypertension_cohort_summary.csv",
                "outputs/reports/diagnosis_cohort_builder_validation_report.md",
                "outputs/reports/config_code_rules_validation.md",
                "outputs/reports/study_config_schema_validation.md",
            ],
            "done": "糖尿病、CKD、心衰和高血压 cohort 均已生成；CKD/心衰/高血压共享 ICD diagnosis-code builder；四个慢病 cohort 的 ICD code rules 已能从 config 读取并通过验证；registry study config schema validation 已覆盖 active MIMIC 和 planned eICU/CHARLS。",
            "next": "继续增强外部数据 readiness 的字段映射；eICU 已完成 first-24h cohort/features/baseline，CHARLS 数据到位后复用同一套 readiness 和 schema validation 模式。",
        },
        {
            "module": "Temporal Feature Agent",
            "percent": 92,
            "evidence": [
                "src/chrono_ehr/mimic_diabetes_lab_features_24h.py",
                "src/chrono_ehr/mimic_diabetes_med_features_24h.py",
                "src/chrono_ehr/mimic_ckd_lab_features.py",
                "src/chrono_ehr/mimic_heart_failure_lab_features.py",
                "src/chrono_ehr/mimic_hypertension_lab_features.py",
                "src/chrono_ehr/mimic_chronic_vital_features.py",
                "src/chrono_ehr/mimic_chronic_procedure_features.py",
                "src/chrono_ehr/mimic_chronic_med_features.py",
                "src/chrono_ehr/feature_window_spec_loader.py",
                "src/chrono_ehr/validate_feature_window_specs.py",
                "src/chrono_ehr/audit_extractor_window_config_usage.py",
                "data/processed/mimic_diabetes_lab_features_24h.csv",
                "data/processed/mimic_ckd_lab_features_24h.csv",
                "data/processed/mimic_ckd_lab_features_discharge.csv",
                "data/processed/mimic_heart_failure_lab_features_24h.csv",
                "data/processed/mimic_heart_failure_lab_features_discharge.csv",
                "data/processed/mimic_hypertension_lab_features_24h.csv",
                "data/processed/mimic_hypertension_lab_features_discharge.csv",
                "data/processed/mimic_diabetes_vital_features_24h.csv",
                "data/processed/mimic_diabetes_vital_features_discharge.csv",
                "data/processed/mimic_ckd_vital_features_24h.csv",
                "data/processed/mimic_ckd_vital_features_discharge.csv",
                "data/processed/mimic_heart_failure_vital_features_24h.csv",
                "data/processed/mimic_heart_failure_vital_features_discharge.csv",
                "data/processed/mimic_hypertension_vital_features_24h.csv",
                "data/processed/mimic_hypertension_vital_features_discharge.csv",
                "data/processed/mimic_diabetes_procedure_features_24h.csv",
                "data/processed/mimic_diabetes_procedure_features_discharge.csv",
                "data/processed/mimic_ckd_procedure_features_24h.csv",
                "data/processed/mimic_ckd_procedure_features_discharge.csv",
                "data/processed/mimic_heart_failure_procedure_features_24h.csv",
                "data/processed/mimic_heart_failure_procedure_features_discharge.csv",
                "data/processed/mimic_hypertension_procedure_features_24h.csv",
                "data/processed/mimic_hypertension_procedure_features_discharge.csv",
                "data/processed/mimic_diabetes_general_med_features_24h.csv",
                "data/processed/mimic_diabetes_general_med_features_discharge.csv",
                "data/processed/mimic_ckd_general_med_features_24h.csv",
                "data/processed/mimic_ckd_general_med_features_discharge.csv",
                "data/processed/mimic_heart_failure_general_med_features_24h.csv",
                "data/processed/mimic_heart_failure_general_med_features_discharge.csv",
                "data/processed/mimic_hypertension_general_med_features_24h.csv",
                "data/processed/mimic_hypertension_general_med_features_discharge.csv",
                "outputs/tables/chronic_disease_vital_feature_availability.csv",
                "outputs/tables/chronic_disease_procedure_feature_availability.csv",
                "outputs/tables/chronic_disease_general_med_feature_availability.csv",
                "outputs/reports/feature_window_spec_validation_report.md",
                "outputs/reports/extractor_window_config_usage_report.md",
                "outputs/tables/extractor_window_config_usage.csv",
                "outputs/reports/chronic_disease_vital_feature_report.md",
                "outputs/reports/chronic_disease_procedure_feature_report.md",
                "outputs/reports/chronic_disease_general_med_feature_report.md",
            ],
            "done": "已支持糖尿病 24h labs/meds，CKD、心衰、高血压的 24h/discharge labs，四个队列共享的 ICU vital-sign、procedure-event 和 broad medication 24h/discharge 特征抽取，feature-window specs validation，以及 extractor window-config usage audit。",
            "next": "继续做 feature selection/降维和缺失模式解释，避免新增变量过多时只看性能不看可解释性。",
        },
        {
            "module": "Leakage Audit Agent",
            "percent": 93,
            "evidence": [
                "src/chrono_ehr/sensitivity_tools.py",
                "src/chrono_ehr/audit_feature_time_map.py",
                "src/chrono_ehr/leakage_gate.py",
                "src/chrono_ehr/run_ed_los_sensitivity.py",
                "outputs/reports/mimic_diabetes_leakage_sensitivity_report.md",
                "outputs/reports/mimic_ckd_leakage_sensitivity_report.md",
                "outputs/reports/mimic_heart_failure_leakage_sensitivity_report.md",
                "outputs/reports/mimic_hypertension_leakage_sensitivity_report.md",
                "outputs/reports/mimic_diabetes_feature_time_audit_report.md",
                "outputs/reports/mimic_ckd_feature_time_audit_report.md",
                "outputs/reports/mimic_heart_failure_feature_time_audit_report.md",
                "outputs/reports/mimic_hypertension_feature_time_audit_report.md",
                "outputs/reports/prediction_time_leakage_gate_report.md",
                "outputs/reports/chronic_disease_ed_los_sensitivity_report.md",
                "outputs/tables/prediction_time_leakage_gate.csv",
                "outputs/tables/prediction_time_leakage_gate_action_items.csv",
                "outputs/tables/chronic_disease_ed_los_sensitivity_comparison.csv",
            ],
            "done": "已完成四个队列的 leakage sensitivity、feature-time audit、prediction-time leakage gate、Beginner Interpretation、action items，以及去掉 ed_los_hours 的 24h 边界变量敏感性分析。",
            "next": "继续把更多 leakage action items 自动转成 sensitivity specs，并把审计结果做成可配置的 manuscript/report sections。",
        },
        {
            "module": "Benchmark Agent",
            "percent": 99,
            "evidence": [
                "src/chrono_ehr/prediction_time_model_tools.py",
                "src/chrono_ehr/prediction_time_spec_loader.py",
                "src/chrono_ehr/validate_prediction_time_specs.py",
                "src/chrono_ehr/check_model_dependencies.py",
                "src/chrono_ehr/random_forest_baseline.py",
                "src/chrono_ehr/calibrated_random_forest_baseline.py",
                "src/chrono_ehr/gradient_boosting_baseline.py",
                "src/chrono_ehr/calibrated_gradient_boosting_baseline.py",
                "src/chrono_ehr/summarize_model_baselines.py",
                "src/chrono_ehr/summarize_model_calibration.py",
                "src/chrono_ehr/summarize_feature_group_ablation.py",
                "src/chrono_ehr/summarize_feature_selection.py",
                "src/chrono_ehr/run_selected_feature_sets.py",
                "src/chrono_ehr/summarize_selected_feature_calibration.py",
                "src/chrono_ehr/run_ed_los_sensitivity.py",
                "src/chrono_ehr/summarize_threshold_analysis.py",
                "src/chrono_ehr/summarize_decision_curve.py",
                "src/chrono_ehr/summarize_subgroup_analysis.py",
                "src/chrono_ehr/plot_summary_figures.py",
                "src/chrono_ehr/generate_supplementary_appendix.py",
                "configs/prediction_time_model_specs.json",
                "outputs/tables/mimic_diabetes_prediction_time_model_performance.csv",
                "outputs/tables/mimic_ckd_prediction_time_model_performance.csv",
                "outputs/tables/mimic_heart_failure_prediction_time_model_performance.csv",
                "outputs/tables/mimic_hypertension_prediction_time_model_performance.csv",
                "outputs/tables/chronic_disease_prediction_time_benchmark.csv",
                "outputs/tables/chronic_disease_prediction_time_deltas.csv",
                "outputs/tables/random_forest_baseline_performance.csv",
                "outputs/tables/calibrated_random_forest_performance.csv",
                "outputs/tables/gradient_boosting_baseline_performance.csv",
                "outputs/tables/gradient_boosting_baseline_status.csv",
                "outputs/tables/calibrated_gradient_boosting_performance.csv",
                "outputs/tables/calibrated_gradient_boosting_predictions.csv",
                "outputs/tables/chronic_disease_model_baseline_comparison.csv",
                "outputs/tables/chronic_disease_model_baseline_delta.csv",
                "outputs/tables/chronic_disease_model_calibration_summary.csv",
                "outputs/tables/chronic_disease_model_calibration_deciles.csv",
                "outputs/tables/chronic_disease_feature_group_ablation.csv",
                "outputs/tables/chronic_disease_feature_group_ablation_summary.csv",
                "outputs/tables/chronic_disease_top_clinical_features.csv",
                "outputs/tables/chronic_disease_feature_selection_group_summary.csv",
                "outputs/tables/chronic_disease_repeated_feature_concepts.csv",
                "outputs/tables/chronic_disease_selected_feature_set_performance.csv",
                "outputs/tables/chronic_disease_selected_feature_set_comparison.csv",
                "outputs/tables/chronic_disease_selected_feature_set_features.csv",
                "outputs/tables/chronic_disease_selected_feature_set_calibration_summary.csv",
                "outputs/tables/chronic_disease_selected_feature_set_supplementary_table.csv",
                "outputs/tables/chronic_disease_ed_los_sensitivity_performance.csv",
                "outputs/tables/chronic_disease_ed_los_sensitivity_comparison.csv",
                "outputs/tables/chronic_disease_threshold_analysis.csv",
                "outputs/tables/chronic_disease_decision_curve.csv",
                "outputs/tables/chronic_disease_subgroup_performance.csv",
                "outputs/reports/model_dependency_status.md",
                "outputs/reports/random_forest_baseline_report.md",
                "outputs/reports/calibrated_random_forest_report.md",
                "outputs/reports/gradient_boosting_baseline_report.md",
                "outputs/reports/calibrated_gradient_boosting_report.md",
                "outputs/reports/chronic_disease_model_baseline_comparison.md",
                "outputs/reports/chronic_disease_model_calibration_report.md",
                "outputs/reports/chronic_disease_feature_group_ablation_report.md",
                "outputs/reports/chronic_disease_feature_selection_report.md",
                "outputs/reports/chronic_disease_selected_feature_set_report.md",
                "outputs/reports/chronic_disease_selected_feature_set_calibration_report.md",
                "outputs/reports/chronic_disease_ed_los_sensitivity_report.md",
                "outputs/reports/chronic_disease_threshold_analysis_report.md",
                "outputs/reports/chronic_disease_decision_curve_report.md",
                "outputs/reports/chronic_disease_subgroup_performance_report.md",
                "outputs/reports/chronic_disease_summary_figures_report.md",
                "outputs/reports/delivery_readiness_audit.md",
                "outputs/tables/delivery_readiness_audit.csv",
                "outputs/figures/chronic_disease_decision_curve_net_benefit.png",
                "outputs/figures/chronic_disease_subgroup_mean_auroc.png",
                "outputs/figures/chronic_disease_subgroup_event_rate_top10_ppv.png",
                "outputs/reports/chronic_disease_supplementary_appendix.md",
                "outputs/reports/chronic_disease_methods_results_draft.md",
            ],
            "done": "已支持 JSON specs 驱动的通用 logistic regression、vital/procedure/medication-augmented prediction-time baselines、Random Forest、calibrated Random Forest、dependency-light HistGradientBoosting、calibrated HistGradientBoosting、跨队列模型对照、特征组 ablation、细粒度 feature selection、selected feature set 对照与校准补充表、ED LOS sensitivity、threshold/alert-burden analysis、decision-curve net benefit、subgroup performance summary、summary figures、delivery readiness audit、manuscript-ready supplementary appendix、校准十分位报告和模型依赖检查。",
            "next": "安装依赖后补跑 XGBoost/LightGBM，或增加外部验证摘要和更多 publication-style figures。",
        },
        {
            "module": "Report Agent",
            "percent": 100,
            "evidence": [
                "src/chrono_ehr/export_manuscript_docx.py",
                "src/chrono_ehr/export_english_brief_docx.py",
                "src/chrono_ehr/generate_single_study_methods_results.py",
                "src/chrono_ehr/report_preset_discovery.py",
                "src/chrono_ehr/build_manuscript_asset_manifest.py",
                "src/chrono_ehr/generate_english_brief_methods_results.py",
                "src/chrono_ehr/audit_english_brief.py",
                "src/chrono_ehr/audit_english_brief_docx.py",
                "docs/english_manuscript_preset_plan.md",
                "configs/manuscript_export_template.json",
                "configs/manuscript_export_template.yaml",
                "configs/manuscript_export_brief.json",
                "configs/manuscript_export_english_brief.json",
                "configs/report_text_templates_english_brief.json",
                "outputs/reports/mimic_diabetes_methods_results_draft.md",
                "outputs/reports/mimic_ckd_methods_results_draft.md",
                "outputs/reports/mimic_heart_failure_methods_results_draft.md",
                "outputs/reports/mimic_heart_failure_lab_feature_report.md",
                "outputs/reports/mimic_heart_failure_prediction_time_model_report.md",
                "outputs/reports/mimic_heart_failure_outcome_sensitivity_report.md",
                "outputs/reports/mimic_hypertension_methods_results_draft.md",
                "outputs/reports/mimic_hypertension_prediction_time_model_report.md",
                "outputs/reports/mimic_hypertension_lab_feature_report.md",
                "outputs/reports/mimic_hypertension_prediction_time_figure_report.md",
                "outputs/reports/mimic_hypertension_outcome_sensitivity_report.md",
                "outputs/reports/chronic_disease_benchmark_report.md",
                "outputs/reports/chronic_disease_benchmark_brief.md",
                "outputs/reports/random_forest_baseline_report.md",
                "outputs/reports/calibrated_random_forest_report.md",
                "outputs/reports/chronic_disease_model_baseline_comparison.md",
                "outputs/reports/chronic_disease_model_calibration_report.md",
                "outputs/reports/chronic_disease_methods_results_draft.md",
                "outputs/reports/chronic_disease_supplementary_appendix.md",
                "outputs/reports/chronic_disease_ed_los_sensitivity_report.md",
                "outputs/reports/chronic_disease_threshold_analysis_report.md",
                "outputs/reports/chronic_disease_decision_curve_report.md",
                "outputs/reports/chronic_disease_subgroup_performance_report.md",
                "outputs/reports/chronic_disease_summary_figures_report.md",
                "outputs/reports/delivery_readiness_audit.md",
                "outputs/reports/report_preset_discovery.md",
                "outputs/reports/manuscript_asset_manifest.md",
                "outputs/reports/chronic_disease_methods_results_english_brief.md",
                "outputs/reports/english_brief_quality_audit.md",
                "outputs/reports/english_brief_docx_audit.md",
                "outputs/reports/ChronoEHR_Methods_Results_Draft.docx",
                "outputs/reports/ChronoEHR_Supplementary_Appendix.docx",
                "outputs/reports/ChronoEHR_Methods_Results_Brief.docx",
                "outputs/reports/ChronoEHR_Supplementary_Brief.docx",
                "outputs/reports/ChronoEHR_Methods_Results_English_Brief.docx",
                "outputs/reports/rendered_methods_results/page-1.png",
                "outputs/reports/rendered_supplementary_appendix/page-1.png",
                "outputs/reports/rendered_methods_results_brief/page-1.png",
                "outputs/reports/rendered_supplementary_brief/page-1.png",
                "outputs/reports/rendered_english_brief/page-1.png",
                "outputs/reports/rendered_english_brief/page-2.png",
                "outputs/reports/rendered_english_brief/page-3.png",
                "outputs/reports/chronic_disease_vital_feature_report.md",
                "outputs/tables/chronic_disease_manuscript_table1.csv",
                "outputs/tables/chronic_disease_manuscript_prediction_time_table.csv",
                "outputs/tables/chronic_disease_prediction_time_deltas.csv",
                "outputs/tables/chronic_disease_medication_increment_table.csv",
                "outputs/tables/chronic_disease_feature_group_ablation_summary.csv",
                "outputs/tables/supplementary_appendix/table_s5_selected_feature_set_comparison.csv",
                "outputs/tables/supplementary_appendix/table_s7_ed_los_sensitivity.csv",
                "outputs/tables/supplementary_appendix/table_s8_threshold_analysis.csv",
                "outputs/tables/supplementary_appendix/table_s9_decision_curve.csv",
                "outputs/tables/supplementary_appendix/table_s10_subgroup_performance.csv",
                "outputs/tables/chronic_disease_manuscript_model_table.csv",
                "outputs/tables/report_preset_discovery.csv",
                "outputs/tables/manuscript_asset_manifest.csv",
                "outputs/tables/english_brief_key_results.csv",
                "outputs/tables/english_brief_quality_audit.csv",
                "outputs/tables/english_brief_docx_audit.csv",
                "outputs/figures/mimic_heart_failure_prediction_time_auroc.png",
                "outputs/figures/mimic_heart_failure_prediction_time_auprc.png",
                "outputs/figures/mimic_hypertension_prediction_time_auroc.png",
                "outputs/figures/mimic_hypertension_prediction_time_auprc.png",
                "outputs/figures/chronic_disease_prediction_time_auroc.png",
                "outputs/figures/chronic_disease_prediction_time_auprc.png",
                "outputs/figures/chronic_disease_model_calibration_deciles.png",
                "outputs/figures/chronic_disease_decision_curve_net_benefit.png",
                "outputs/figures/chronic_disease_subgroup_mean_auroc.png",
                "outputs/figures/chronic_disease_subgroup_event_rate_top10_ppv.png",
            ],
            "done": "已输出四个 MIMIC 慢病单队列和跨队列 Methods/Results 草稿、英文 brief Markdown 草稿和质量审计、英文 brief DOCX review draft 与渲染页审计、写作资产 manifest、跨慢病 benchmark 长报告/brief、vital/procedure/medication 增量表、feature-group ablation 表、selected/full supplementary appendix、ED LOS sensitivity section、threshold/alert-burden section、decision-curve section、subgroup performance section、配置驱动 DOCX export、完整/brief Word 包、report preset discovery、Random Forest / calibrated RF 报告、校准报告、manuscript-ready 表格和核心图表。",
            "next": "继续补期刊格式 preset，并把英文 review draft 的人工润色意见逐步并入正式 manuscript exporter。",
        },
        {
            "module": "External Benchmark Agent",
            "percent": 95,
            "evidence": [
                "docs/external_validation_plan.md",
                "docs/multidatabase_expansion_plan.md",
                "docs/multidatabase_task_matrix.csv",
                "docs/eicu_charls_next_steps.md",
                "docs/eicu_temporal_mortality_protocol.md",
                "docs/charls_incident_diabetes_protocol.md",
                "docs/eicu_feature_time_map_template.csv",
                "docs/charls_wave_map_template.csv",
                "docs/eicu_leakage_checklist.md",
                "docs/charls_leakage_checklist.md",
                "configs/eicu_temporal_mortality_template.yaml",
                "configs/charls_incident_diabetes_template.yaml",
                "src/chrono_ehr/cdsl_external_validation_readiness.py",
                "src/chrono_ehr/cdsl_temporal_benchmark.py",
                "src/chrono_ehr/cdsl_leakage_audit.py",
                "src/chrono_ehr/cdsl_traditional_baselines.py",
                "src/chrono_ehr/plot_cdsl_benchmark_figures.py",
                "src/chrono_ehr/eicu_data_readiness.py",
                "src/chrono_ehr/eicu_temporal_mortality_cohort.py",
                "src/chrono_ehr/validate_eicu_temporal_mortality_cohort.py",
                "src/chrono_ehr/eicu_temporal_features_24h.py",
                "src/chrono_ehr/validate_eicu_temporal_features_24h.py",
                "src/chrono_ehr/eicu_leakage_gate.py",
                "src/chrono_ehr/eicu_first24h_logistic_baseline.py",
                "src/chrono_ehr/validate_eicu_first24h_baseline.py",
                "src/chrono_ehr/eicu_baseline_figures.py",
                "src/chrono_ehr/validate_eicu_baseline_figures.py",
                "src/chrono_ehr/charls_data_readiness.py",
                "src/chrono_ehr/summarize_external_readiness.py",
                "src/chrono_ehr/external_benchmark_summary_table.py",
                "src/chrono_ehr/validate_external_benchmark_summary_table.py",
                "src/chrono_ehr/external_field_role_catalog.py",
                "src/chrono_ehr/validate_external_field_role_catalog.py",
                "src/chrono_ehr/next_study_planner.py",
                "outputs/reports/cdsl_external_validation_readiness_report.md",
                "outputs/reports/cdsl_temporal_benchmark_report.md",
                "outputs/reports/cdsl_leakage_audit_report.md",
                "outputs/reports/cdsl_traditional_baselines_report.md",
                "outputs/reports/cdsl_summary_figures_report.md",
                "outputs/reports/eicu_data_readiness_report.md",
                "outputs/reports/eicu_temporal_mortality_cohort_report.md",
                "outputs/reports/eicu_temporal_mortality_cohort_validation.md",
                "outputs/reports/eicu_temporal_features_24h_report.md",
                "outputs/reports/eicu_temporal_features_24h_validation.md",
                "outputs/reports/eicu_leakage_gate_report.md",
                "outputs/reports/eicu_first24h_logistic_baseline_report.md",
                "outputs/reports/eicu_first24h_logistic_baseline_validation.md",
                "outputs/reports/eicu_baseline_figures_report.md",
                "outputs/reports/eicu_baseline_figures_validation.md",
                "outputs/reports/charls_data_readiness_report.md",
                "outputs/reports/external_benchmark_readiness_summary.md",
                "outputs/reports/external_benchmark_summary_table.md",
                "outputs/reports/external_benchmark_summary_validation.md",
                "outputs/reports/external_field_role_catalog.md",
                "outputs/reports/external_field_role_catalog_validation.md",
                "outputs/reports/next_study_action_plan.md",
                "outputs/tables/cdsl_external_validation_candidate_paths.csv",
                "outputs/tables/cdsl_external_validation_file_inventory.csv",
                "outputs/tables/cdsl_external_validation_schema_candidates.csv",
                "outputs/tables/cdsl_external_validation_fold_audit.csv",
                "outputs/tables/cdsl_external_validation_summary.csv",
                "outputs/tables/cdsl_temporal_benchmark_metrics.csv",
                "outputs/tables/cdsl_temporal_benchmark_window_audit.csv",
                "outputs/tables/cdsl_leakage_audit.csv",
                "outputs/tables/cdsl_traditional_baselines_metrics.csv",
                "outputs/tables/cdsl_traditional_baselines_window_audit.csv",
                "outputs/tables/supplementary_appendix/table_s11_cdsl_external_benchmark.csv",
                "outputs/tables/supplementary_appendix/table_s12_cdsl_leakage_audit.csv",
                "outputs/tables/supplementary_appendix/table_s13_external_benchmark_summary.csv",
                "outputs/tables/eicu_data_readiness_candidate_paths.csv",
                "outputs/tables/eicu_data_readiness_expected_tables.csv",
                "outputs/tables/eicu_schema_mapping_draft.csv",
                "data/processed/eicu_temporal_mortality_cohort.csv",
                "data/processed/eicu_lab_features_24h.csv",
                "data/processed/eicu_vital_features_24h.csv",
                "data/processed/eicu_first24h_feature_matrix_skeleton.csv",
                "outputs/tables/eicu_temporal_mortality_cohort_summary.csv",
                "outputs/tables/eicu_temporal_mortality_cohort_exclusions.csv",
                "outputs/tables/eicu_temporal_mortality_split_summary.csv",
                "outputs/tables/eicu_temporal_mortality_cohort_validation.csv",
                "outputs/tables/eicu_temporal_features_24h_availability.csv",
                "outputs/tables/eicu_temporal_features_24h_extraction_stats.csv",
                "outputs/tables/eicu_temporal_features_24h_validation.csv",
                "outputs/tables/eicu_leakage_gate.csv",
                "outputs/tables/eicu_first24h_logistic_baseline_metrics.csv",
                "outputs/tables/eicu_first24h_logistic_baseline_predictions.csv",
                "outputs/tables/eicu_first24h_logistic_baseline_coefficients.csv",
                "outputs/tables/eicu_first24h_logistic_baseline_validation.csv",
                "outputs/tables/eicu_first24h_calibration_deciles.csv",
                "outputs/tables/eicu_first24h_calibration_summary.csv",
                "outputs/tables/eicu_baseline_figures_validation.csv",
                "outputs/tables/charls_data_readiness_candidate_paths.csv",
                "outputs/tables/charls_wave_detection.csv",
                "outputs/tables/charls_schema_mapping_draft.csv",
                "outputs/tables/charls_proposed_tasks.csv",
                "outputs/tables/external_benchmark_readiness_summary.csv",
                "outputs/tables/external_benchmark_summary_table.csv",
                "outputs/tables/external_benchmark_summary_validation.csv",
                "outputs/tables/external_field_role_catalog.csv",
                "outputs/tables/external_field_role_summary.csv",
                "outputs/tables/external_field_role_catalog_validation.csv",
                "outputs/tables/next_study_action_plan.csv",
                "outputs/figures/cdsl_temporal_benchmark_auroc.png",
                "outputs/figures/cdsl_temporal_benchmark_auprc.png",
                "outputs/figures/eicu_first24h_logistic_roc.png",
                "outputs/figures/eicu_first24h_logistic_precision_recall.png",
                "outputs/figures/eicu_first24h_logistic_calibration_deciles.png",
            ],
            "done": "已完成 CDSL 路径发现、schema/fold readiness、temporal benchmark、leakage audit、logistic/Random Forest/HistGradientBoosting 传统模型对照、AUROC/AUPRC summary figures，并已加入 supplementary appendix Table S11/S12。已新增 eICU/CHARLS 多数据库扩展计划、readiness 脚本、protocol/config 模板、时间点映射模板、leakage checklist、external readiness summary、统一 field-role catalog、next study action planner 和 CDSL/eICU external benchmark summary table；eICU first-24h hospital mortality cohort、lab/vital feature skeleton、leakage gate、lightweight logistic baseline、ROC/PR figures 和 calibration summary 已完成，CHARLS 仍为 DATA_PENDING。",
            "next": "后续保持 external benchmark summary table 随 CDSL/eICU 输出更新；CHARLS 数据落地后复跑 readiness，再进入 wave 字段映射和第一个 baseline。",
        },
        {
            "module": "Study Registry / Runner",
            "percent": 99,
            "evidence": [
                "configs/study_registry.json",
                "configs/manuscript_export_template.json",
                "configs/manuscript_export_brief.json",
                "configs/agent_action_catalog.json",
                "configs/agent_demo_workflows.json",
                "configs/agent_entrypoints.json",
                "src/chrono_ehr/run_study.py",
                "src/chrono_ehr/run_agent_demo_workflow.py",
                "src/chrono_ehr/validate_agent_demo_workflow.py",
                "src/chrono_ehr/generate_agent_entrypoints.py",
                "src/chrono_ehr/validate_mainline_mvp.py",
                "src/chrono_ehr/audit_config_coverage.py",
                "src/chrono_ehr/generate_config_migration_backlog.py",
                "src/chrono_ehr/validate_config_code_rules.py",
                "src/chrono_ehr/validate_study_config_schema.py",
                "src/chrono_ehr/cdsl_external_validation_readiness.py",
                "src/chrono_ehr/cdsl_temporal_benchmark.py",
                "src/chrono_ehr/cdsl_leakage_audit.py",
                "src/chrono_ehr/cdsl_traditional_baselines.py",
                "src/chrono_ehr/plot_cdsl_benchmark_figures.py",
                "src/chrono_ehr/eicu_data_readiness.py",
                "src/chrono_ehr/eicu_baseline_figures.py",
                "src/chrono_ehr/validate_eicu_baseline_figures.py",
                "src/chrono_ehr/external_benchmark_summary_table.py",
                "src/chrono_ehr/validate_external_benchmark_summary_table.py",
                "src/chrono_ehr/charls_data_readiness.py",
                "src/chrono_ehr/summarize_external_readiness.py",
                "src/chrono_ehr/next_study_planner.py",
                "src/chrono_ehr/study_capability_audit.py",
                "src/chrono_ehr/pipeline_step_introspection.py",
                "src/chrono_ehr/agent_control_panel.py",
                "src/chrono_ehr/validate_agent_control_panel.py",
                "src/chrono_ehr/agent_task_router.py",
                "src/chrono_ehr/agent_task_queue.py",
                "src/chrono_ehr/agent_task_scenario_library.py",
                "src/chrono_ehr/validate_agent_task_router.py",
                "src/chrono_ehr/validate_agent_task_queue.py",
                "src/chrono_ehr/validate_agent_task_scenarios.py",
                "src/chrono_ehr/validate_agent_task_execution.py",
                "src/chrono_ehr/validate_agent_action_catalog.py",
                "src/chrono_ehr/agent_command_linter.py",
                "src/chrono_ehr/agent_boundary_audit.py",
                "src/chrono_ehr/agent_artifact_freshness.py",
                "src/chrono_ehr/agent_doctor.py",
                "src/chrono_ehr/validate_agent_doctor.py",
                "src/chrono_ehr/agent_control_consistency_audit.py",
                "src/chrono_ehr/build_agent_state.py",
                "src/chrono_ehr/validate_agent_state.py",
                "src/chrono_ehr/agent_self_check.py",
                "src/chrono_ehr/agent_recovery_planner.py",
                "src/chrono_ehr/agent_runbook.py",
                "src/chrono_ehr/validate_agent_runbook.py",
                "src/chrono_ehr/validate_agent_runbook_confirmation.py",
                "src/chrono_ehr/agent_runbook_state_machine.py",
                "src/chrono_ehr/validate_agent_runbook_state_machine.py",
                "src/chrono_ehr/agent_runbook_retry_planner.py",
                "src/chrono_ehr/validate_agent_runbook_retry_plan.py",
                "src/chrono_ehr/agent_next_task_planner.py",
                "src/chrono_ehr/validate_agent_next_tasks.py",
                "src/chrono_ehr/report_preset_discovery.py",
                "src/chrono_ehr/build_manuscript_asset_manifest.py",
                "src/chrono_ehr/export_english_brief_docx.py",
                "src/chrono_ehr/audit_english_brief_docx.py",
                "src/chrono_ehr/export_manuscript_docx.py",
                "src/chrono_ehr/run_ed_los_sensitivity.py",
                "src/chrono_ehr/summarize_threshold_analysis.py",
                "src/chrono_ehr/summarize_decision_curve.py",
                "src/chrono_ehr/summarize_subgroup_analysis.py",
                "src/chrono_ehr/plot_summary_figures.py",
                "src/chrono_ehr/delivery_readiness_audit.py",
                "src/chrono_ehr/run_diabetes_demo.py",
                "src/chrono_ehr/run_ckd_demo.py",
                "src/chrono_ehr/run_heart_failure_demo.py",
                "src/chrono_ehr/run_hypertension_demo.py",
                "outputs/reports/prediction_time_spec_validation_report.md",
                "outputs/reports/feature_window_spec_validation_report.md",
                "outputs/reports/extractor_window_config_usage_report.md",
                "outputs/reports/study_registry_validation_report.md",
                "outputs/reports/diagnosis_cohort_builder_validation_report.md",
                "outputs/reports/next_study_action_plan.md",
                "outputs/reports/study_capability_audit.md",
                "outputs/reports/pipeline_step_introspection.md",
                "outputs/reports/agent_control_panel.md",
                "outputs/reports/agent_control_routing_validation.md",
                "outputs/reports/agent_entrypoints.md",
                "outputs/reports/mainline_mvp_validation.md",
                "outputs/reports/config_coverage_audit.md",
                "outputs/reports/config_migration_backlog.md",
                "outputs/reports/config_code_rules_validation.md",
                "outputs/reports/study_config_schema_validation.md",
                "outputs/reports/agent_task_plan.md",
                "outputs/reports/agent_task_queue.md",
                "outputs/reports/agent_task_queue_validation.md",
                "outputs/reports/agent_task_router_validation.md",
                "outputs/reports/agent_task_scenario_library.md",
                "outputs/reports/agent_task_scenario_library_validation.md",
                "outputs/reports/agent_task_execution_validation.md",
                "outputs/reports/agent_action_catalog_validation.md",
                "outputs/reports/agent_command_lint.md",
                "outputs/reports/agent_boundary_audit.md",
                "outputs/reports/agent_artifact_freshness.md",
                "outputs/reports/agent_doctor.md",
                "outputs/reports/agent_doctor_validation.md",
                "outputs/reports/agent_control_consistency_audit.md",
                "outputs/reports/agent_demo_workflow_diabetes.md",
                "outputs/reports/agent_demo_workflow_validation.md",
                "outputs/reports/agent_self_check.md",
                "outputs/reports/agent_recovery_plan.md",
                "outputs/reports/agent_runbook.md",
                "outputs/reports/agent_runbook_validation.md",
                "outputs/reports/agent_runbook_confirmation_validation.md",
                "outputs/reports/agent_runbook_state_machine.md",
                "outputs/reports/agent_runbook_state_machine_validation.md",
                "outputs/reports/agent_runbook_retry_plan.md",
                "outputs/reports/agent_runbook_retry_plan_validation.md",
                "outputs/reports/agent_next_tasks.md",
                "outputs/reports/agent_next_tasks_validation.md",
                "outputs/reports/agent_state_validation.md",
                "outputs/reports/report_preset_discovery.md",
                "outputs/reports/manuscript_asset_manifest.md",
                "outputs/reports/english_brief_docx_audit.md",
                "outputs/tables/study_capability_audit.csv",
                "outputs/tables/study_capability_summary.csv",
                "outputs/tables/pipeline_step_introspection.csv",
                "outputs/tables/pipeline_step_summary.csv",
                "outputs/tables/agent_control_study_state.csv",
                "outputs/tables/agent_control_external_state.csv",
                "outputs/tables/agent_control_recommended_actions.csv",
                "outputs/tables/agent_control_routing_validation.csv",
                "outputs/tables/agent_entrypoints.csv",
                "outputs/tables/mainline_mvp_validation.csv",
                "outputs/tables/config_coverage_audit.csv",
                "outputs/tables/config_coverage_summary.csv",
                "outputs/tables/config_migration_backlog.csv",
                "outputs/tables/config_code_rules_validation.csv",
                "outputs/tables/study_config_schema_validation.csv",
                "outputs/tables/agent_task_plan.csv",
                "outputs/tables/agent_task_scenario.csv",
                "outputs/tables/agent_task_queue.csv",
                "outputs/tables/agent_task_queue_validation.csv",
                "outputs/tables/agent_task_scenario_library.csv",
                "outputs/tables/agent_task_scenario_examples.csv",
                "outputs/tables/agent_task_scenario_library_validation.csv",
                "outputs/tables/agent_task_deferred_actions.csv",
                "outputs/tables/agent_task_execution.csv",
                "outputs/tables/agent_task_post_run_refresh.csv",
                "outputs/tables/agent_task_router_validation.csv",
                "outputs/tables/agent_task_execution_validation.csv",
                "outputs/tables/agent_action_catalog_validation.csv",
                "outputs/tables/agent_command_lint.csv",
                "outputs/tables/agent_boundary_audit.csv",
                "outputs/tables/agent_artifact_freshness.csv",
                "outputs/tables/agent_doctor.csv",
                "outputs/tables/agent_doctor_validation.csv",
                "outputs/tables/agent_control_consistency_audit.csv",
                "outputs/tables/agent_demo_workflow_diabetes.csv",
                "outputs/tables/agent_demo_workflow_validation.csv",
                "outputs/tables/agent_self_check.csv",
                "outputs/tables/agent_recovery_plan.csv",
                "outputs/tables/agent_recovery_execution.csv",
                "outputs/tables/agent_runbook.csv",
                "outputs/tables/agent_runbook_execution.csv",
                "outputs/tables/agent_runbook_phase_summary.csv",
                "outputs/tables/agent_runbook_validation.csv",
                "outputs/tables/agent_runbook_confirmation_validation.csv",
                "outputs/tables/agent_runbook_state_machine.csv",
                "outputs/tables/agent_runbook_state_machine_validation.csv",
                "outputs/tables/agent_runbook_retry_plan.csv",
                "outputs/tables/agent_runbook_retry_plan_validation.csv",
                "outputs/tables/agent_next_tasks.csv",
                "outputs/tables/agent_next_tasks_validation.csv",
                "outputs/tables/agent_state_validation.csv",
                "outputs/tables/report_preset_discovery.csv",
                "outputs/tables/manuscript_asset_manifest.csv",
                "outputs/tables/english_brief_docx_audit.csv",
                "outputs/state/agent_state.json",
                "outputs/state/agent_state.md",
                "outputs/state/agent_task_history.csv",
                "outputs/state/agent_demo_workflow_diabetes.json",
                "outputs/state/agent_runbook_history.csv",
                "outputs/state/agent_runbook_state_machine.json",
                "outputs/state/agent_runbook_phase_history.csv",
            ],
            "done": "已有 study registry、统一主入口、四个队列 runner、registry validation、prediction spec validation、feature-window validation、extractor-window audit、diagnosis builder validation、config coverage audit、config migration backlog、benchmark-summary、shared feature extraction、ED LOS sensitivity、threshold analysis、decision-curve analysis、subgroup analysis、summary figures、delivery readiness audit、study capability audit、pipeline step introspection、一键 diabetes Agent demo workflow、demo workflow validation、stable entrypoint index、mainline MVP validation gate、Agent control panel、自然语言 agent-task router、safe/expensive/model/report 动作风险分级、low_quota/normal/night-run budget mode、task scenario template layer、task scenario library/export/validation、phase/execution_policy、按预算执行 safe actions、deferred actions、agent-task post-run refresh、task execution validation、夜间 phased runbook、runbook validation、runbook state machine、phase history、attempt count、next allowed command、expensive phase 显式确认门、确认门回归测试、post-phase state/recovery/next-task refresh、next-task planner、next-task safety validation、action catalog validation、command lint、boundary audit、artifact freshness audit、Agent doctor、Agent doctor validation、Agent control consistency audit、state freshness audit、task-router validation、persistent agent_state、agent_state stale-memory validation、recent task history、last task execution memory、last runbook memory、runbook history、agent self-check、agent recovery planner 与可选 safe recovery execution、status card Last Task 摘要、report preset discovery、manuscript asset manifest、CDSL external benchmark 命令、eICU baseline-ready 外部 ICU benchmark 命令、CHARLS readiness 命令、eICU baseline figures/calibration 命令、external benchmark summary 命令、external readiness summary 命令、next study plan 命令。",
            "next": "继续增强自然语言任务的可解释执行策略和外部数据感知能力；CHARLS 数据落地后接入 readiness-driven 纵向慢病工作流。",
        },
    ]

    for module in modules:
        evidence = module["evidence"]
        existing = [path for path in evidence if exists(project, path)]
        module["evidence_existing"] = existing
        module["evidence_missing"] = [path for path in evidence if path not in existing]
    return modules


def overall_percent(modules: list[dict[str, Any]]) -> int:
    return round(sum(module["percent"] for module in modules) / len(modules))


def write_report(project: Path, registry: dict[str, Any], output: Path) -> None:
    modules = module_status(project)
    overall = overall_percent(modules)
    lines = [
        "# ChronoEHR-Agent Progress Report",
        "",
        f"- Overall estimated progress: **{overall}%** (`{status_label(overall)}`)",
        "- Scope: local EHR research tool for time-aware chronic-disease prediction studies.",
        "- Boundary: not a medical QA Agent and not a clinical diagnosis/treatment recommendation system.",
        "",
        "## Registered Studies",
        "",
        *study_summary(project, registry),
        "",
        "## Module Progress",
        "",
        "| Module | Progress | Status | Current evidence |",
        "|---|---:|---|---:|",
    ]
    for module in modules:
        lines.append(
            f"| {module['module']} | {module['percent']}% | `{status_label(module['percent'])}` | "
            f"{len(module['evidence_existing'])}/{len(module['evidence'])} files |"
        )

    lines.extend(["", "## Module Details", ""])
    for module in modules:
        lines.extend(
            [
                f"### {module['module']}",
                "",
                f"- Progress: {module['percent']}% (`{status_label(module['percent'])}`)",
                f"- Done: {module['done']}",
                f"- Next: {module['next']}",
                "- Evidence:",
            ]
        )
        for path in module["evidence_existing"]:
            lines.append(f"  - `{path}`")
        if module["evidence_missing"]:
            lines.append("- Missing/expected:")
            for path in module["evidence_missing"]:
                lines.append(f"  - `{path}`")
        lines.append("")

    lines.extend(
        [
            "## Immediate Next Steps",
            "",
            "1. Keep polishing the Agent control layer before adding more report-generation features.",
            "2. Add richer natural-language task templates and examples for low-quota, night-run, external-data, and validation-first situations.",
            "3. Keep recovery planning conservative: auto-run only safe validation/refresh actions, and leave expensive/model actions behind explicit gates.",
            "4. Keep eICU as a baseline-ready ICU mortality benchmark; rerun CHARLS readiness after approved waves arrive, then bootstrap the first longitudinal chronic-disease workflow.",
            "",
            "## Reproduction Commands",
            "",
            "```bash",
            f"cd {project}",
            "python3 src/chrono_ehr/run_study.py --list",
            "python3 src/chrono_ehr/run_diabetes_demo.py --skip-existing --no-expensive",
            "python3 src/chrono_ehr/run_ckd_demo.py --skip-existing --no-expensive",
            "python3 src/chrono_ehr/run_heart_failure_demo.py --skip-existing --no-expensive",
            "python3 src/chrono_ehr/run_study.py --single-study-drafts",
            "python3 src/chrono_ehr/run_study.py --study-capabilities",
            "python3 src/chrono_ehr/run_study.py --pipeline-steps",
            "python3 src/chrono_ehr/run_study.py --agent-control --agent-goal status",
            "python3 src/chrono_ehr/run_study.py --diabetes-agent-demo",
            "python3 src/chrono_ehr/run_study.py --validate-agent-demo-workflow",
            "python3 src/chrono_ehr/run_study.py --agent-entrypoints",
            "python3 src/chrono_ehr/run_study.py --validate-mainline-mvp",
            "python3 src/chrono_ehr/run_study.py --config-coverage-audit",
            "python3 src/chrono_ehr/run_study.py --config-migration-backlog",
            "python3 src/chrono_ehr/run_study.py --validate-agent-control",
            "python3 src/chrono_ehr/run_study.py --agent-task \"检查糖尿病 demo 有没有时间点泄漏\"",
            "python3 src/chrono_ehr/run_study.py --agent-task \"我要去睡觉，可以多跑一些但不要重训模型\"",
            "python3 src/chrono_ehr/run_study.py --agent-task \"我快没额度了，只剩2%，做一点简单自检\" --agent-task-execute-safe --agent-task-post-run-refresh",
            "python3 src/chrono_ehr/run_study.py --agent-task-scenarios",
            "python3 src/chrono_ehr/run_study.py --validate-agent-task-scenarios",
            "python3 src/chrono_ehr/run_study.py --validate-agent-task-router",
            "python3 src/chrono_ehr/run_study.py --validate-agent-task-execution",
            "python3 src/chrono_ehr/run_study.py --validate-agent-action-catalog",
            "python3 src/chrono_ehr/run_study.py --agent-command-lint",
            "python3 src/chrono_ehr/run_study.py --agent-doctor",
            "python3 src/chrono_ehr/run_study.py --validate-agent-doctor",
            "python3 src/chrono_ehr/run_study.py --agent-control-consistency",
            "python3 src/chrono_ehr/run_study.py --agent-boundary-audit",
            "python3 src/chrono_ehr/run_study.py --agent-artifact-freshness",
            "python3 src/chrono_ehr/run_study.py --agent-state",
            "python3 src/chrono_ehr/run_study.py --validate-agent-state",
            "python3 src/chrono_ehr/run_study.py --agent-self-check",
            "python3 src/chrono_ehr/run_study.py --agent-recovery-plan",
            "python3 src/chrono_ehr/run_study.py --agent-runbook \"我要去睡觉，电脑不关，可以多跑一些但不要重训模型\"",
            "python3 src/chrono_ehr/run_study.py --agent-runbook \"我要去睡觉，电脑不关，可以多跑一些但不要重训模型\" --agent-runbook-execute-expensive-phase --confirm-expensive --agent-runbook-post-phase-refresh",
            "python3 src/chrono_ehr/run_study.py --validate-agent-runbook",
            "python3 src/chrono_ehr/run_study.py --validate-agent-runbook-confirmation",
            "python3 src/chrono_ehr/run_study.py --agent-runbook-state",
            "python3 src/chrono_ehr/run_study.py --validate-agent-runbook-state",
            "python3 src/chrono_ehr/run_study.py --agent-runbook-retry-plan",
            "python3 src/chrono_ehr/run_study.py --validate-agent-runbook-retry-plan",
            "python3 src/chrono_ehr/run_study.py --agent-next-tasks",
            "python3 src/chrono_ehr/run_study.py --validate-agent-next-tasks",
            "python3 src/chrono_ehr/run_study.py --report-presets",
            "python3 src/chrono_ehr/run_study.py --asset-manifest",
            "python3 src/chrono_ehr/run_study.py --english-brief-draft",
            "python3 src/chrono_ehr/run_study.py --english-brief-audit",
            "python3 src/chrono_ehr/run_study.py --english-brief-docx",
            "python3 src/chrono_ehr/run_study.py --english-brief-docx-audit",
            "python3 src/chrono_ehr/run_study.py --vital-features  # expensive: scans ICU chartevents",
            "python3 src/chrono_ehr/run_study.py --procedure-features",
            "python3 src/chrono_ehr/run_study.py --general-med-features",
            "python3 src/chrono_ehr/run_study.py --benchmark-summary",
            "python3 src/chrono_ehr/run_study.py --random-forest-baseline",
            "python3 src/chrono_ehr/run_study.py --gradient-boosting-baseline",
            "python3 src/chrono_ehr/run_study.py --calibrated-random-forest",
            "python3 src/chrono_ehr/run_study.py --calibrated-gradient-boosting",
            "python3 src/chrono_ehr/run_study.py --model-baseline-summary",
            "python3 src/chrono_ehr/run_study.py --model-calibration-summary",
            "python3 src/chrono_ehr/run_study.py --feature-group-ablation",
            "python3 src/chrono_ehr/run_study.py --feature-selection-summary",
            "python3 src/chrono_ehr/run_study.py --selected-feature-sets",
            "python3 src/chrono_ehr/run_study.py --selected-feature-calibration",
            "python3 src/chrono_ehr/run_study.py --ed-los-sensitivity",
            "python3 src/chrono_ehr/run_study.py --threshold-analysis",
            "python3 src/chrono_ehr/run_study.py --decision-curve",
            "python3 src/chrono_ehr/run_study.py --subgroup-analysis",
            "python3 src/chrono_ehr/run_study.py --summary-figures",
            "python3 src/chrono_ehr/run_study.py --delivery-readiness",
            "python3 src/chrono_ehr/run_study.py --cdsl-readiness",
            "python3 src/chrono_ehr/run_study.py --cdsl-temporal-benchmark",
            "python3 src/chrono_ehr/run_study.py --cdsl-leakage-audit",
            "python3 src/chrono_ehr/run_study.py --cdsl-traditional-baselines",
            "python3 src/chrono_ehr/run_study.py --cdsl-summary-figures",
            "python3 src/chrono_ehr/run_study.py --eicu-readiness",
            "python3 src/chrono_ehr/run_study.py --eicu-baseline-figures",
            "python3 src/chrono_ehr/run_study.py --validate-eicu-baseline-figures",
            "python3 src/chrono_ehr/run_study.py --external-benchmark-summary",
            "python3 src/chrono_ehr/run_study.py --validate-external-benchmark-summary",
            "python3 src/chrono_ehr/run_study.py --charls-readiness",
            "python3 src/chrono_ehr/run_study.py --external-readiness-summary",
            "python3 src/chrono_ehr/run_study.py --next-study-plan",
            "python3 src/chrono_ehr/run_study.py --cross-cohort-draft",
            "python3 src/chrono_ehr/run_study.py --supplementary-appendix",
            "python3 src/chrono_ehr/run_study.py --manuscript-docx",
            "python3 src/chrono_ehr/run_study.py --manuscript-docx --manuscript-export-config configs/manuscript_export_brief.json",
            "python3 src/chrono_ehr/run_study.py --validate-feature-windows",
            "python3 src/chrono_ehr/run_study.py --leakage-gate",
            "python3 src/chrono_ehr/run_study.py --audit-extractor-windows",
            "python3 src/chrono_ehr/run_study.py --validate-diagnosis-builder",
            "python3 src/chrono_ehr/generate_agent_progress_report.py",
            "```",
        ]
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT)
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    parser.add_argument("--output", type=Path, default=PROJECT / "outputs" / "reports" / "agent_progress_report.md")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    registry = load_registry(args.registry)
    write_report(args.project_root, registry, args.output)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
